# 2.1 数据操作
## 2.1.1数组创建

⾸先，我们介绍n维数组，也称为张量（tensor）。n维数组是机器学习和神经网络的主要数据结构，比如0-d（标量）、1-d（向量）、2-d（矩阵）、3-d（一张RGB图片）、4-d（一批RGB图片）、5-d（一个视频批量）等。

创建一个数组，我们需要三个方面的信息：
* 形状：例如（3,4）的举证
* 每个元素的数据类型：例如32位浮点数
* 每个元素的值，例如全零、随机数等

⾸先，我们导⼊torch：

In [ ]:
import torch

张量表⽰由数值组成的数组，这个数组可能有多个维度。具有⼀个轴的张量对应数学上的向量（vector）；具有两个轴的张量对应数学上的矩阵（matrix）；具有两个轴以上的张量没有特殊的数学名称。

首先，我们可以使用arange创建一个行向量x。这个⾏向量包含以0开始的前12个整数，它们默认创建为整数。也可指定创建类型为浮点数。张量中的每个值都称为张量的 元素（element）。例如，张量 x 中有 12 个元素。除⾮额外指定，新的张量将存储在内存中，并采⽤基于CPU的计算。

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的shape属性来访问张量（沿每个轴的⻓度）的形状。

In [3]:
x.shape

torch.Size([12])

如果只想知道张量中元素的总数，即形状的所有元素乘积，可以使用numel来检查它的⼤⼩：

In [5]:
x.numel()

12

要想改变⼀个张量的形状⽽不改变元素数量和元素值，可以调⽤reshape函数。例如，可以把张量x从形状为（12,）的⾏向量转换为形状为（3,4）的矩阵。

In [7]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

我们不需要通过⼿动指定每个维度来改变形状，可以通过-1来调⽤此⾃动计算出维度的功能。即我们可以
⽤x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)

In [9]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

有时，我们希望使⽤全0、全1、其他常量，或者从特定分布中随机采样的数字来初始化矩阵。

我们可以创建⼀个形状为（2,3,4）的张量，其中所有元素都设置为0或者1:

In [11]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

有时我们想通过从某个特定的概率分布中随机采样来得到张量中每个元素的值，比如随机初始化网络参数。

以下代码创建⼀个形状为（3,4）的张量。其中的每个元素都从均值为0、标准差为1的标准⾼斯分布（正态分布）中随机采样。

In [15]:
torch.randn(3,4)

tensor([[-0.6025,  1.2229,  0.9253, -1.0724],
        [ 0.5392, -0.1769,  0.5307, -1.3800],
        [-0.4619,  1.5442,  0.7188,  2.8841]])

从区间[0, 1)的均匀分布中抽取的一组随机数组成（3,4）的矩阵：

In [16]:
torch.rand(3, 4)

tensor([[0.2408, 0.3669, 0.8810, 0.4104],
        [0.3447, 0.8011, 0.3807, 0.4199],
        [0.0196, 0.6255, 0.3990, 0.3051]])

我们还可以通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。在这⾥，最外层的列表对应于轴0，内层的列表对应于轴1。

In [17]:
x = torch.tensor([[5.5, 3], [4.4, 3.5]])
x

tensor([[5.5000, 3.0000],
        [4.4000, 3.5000]])

## 2.1.2 运算操作
我们的兴趣不仅限于读取数据和写入数据。 我们想在这些数据上执行数学运算，其中最简单且最有用的操作是按元素（elementwise）运算。 它们将标准标量运算符应用于数组的每个元素。 对于将两个数组作为输入的函数，按元素运算将二元运算符应用于两个数组中的每对位置对应的元素。

对于任意具有相同形状的张量，
[**常见的标准算术运算符（`+`、`-`、`*`、`/`和`**`）都可以被升级为按元素运算**]。
我们可以在同一形状的任意两个张量上调用按元素操作。
在下面的例子中，我们使用逗号来表示一个具有5个元素的元组，其中每个元素都是按元素操作的结果。

In [19]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

我们也可以把多个张量*连结*（concatenate）在一起，把它们端对端地叠起来形成⼀个更⼤的张量。

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  4.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

有时，我们想通过逻辑运算符构建⼆元张量。以X == Y为例：对于每个位置，如果X和Y在该位置相等，则
新张量中相应项的值为1。这意味着逻辑语句X == Y在该位置处为真，否则该位置为0。

In [22]:
X == Y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进⾏求和，会产⽣⼀个单元素张量:

In [23]:
X.sum()

tensor(66.)

## 2.1.3广播机制
在上⾯的部分中，我们看到了如何在相同形状的两个张量上执⾏按元素操作。在某些情况下，即使形状不同，
我们仍然可以通过调⽤ ⼴播机制（broadcasting mechanism）来执⾏按元素操作。这种机制的⼯作⽅式如
下：⾸先，通过适当复制元素来扩展⼀个或两个数组，以便在转换之后，两个张量具有相同的形状。其次，对
⽣成的数组执⾏按元素操作。
在⼤多数情况下，我们将沿着数组中⻓度为1的轴进⾏⼴播，如下例⼦：

In [25]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [26]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4 索引和切片

In [27]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
# 最后一行元素
X[-1]

tensor([ 8.,  9., 10., 11.])

In [30]:
# 第1行和第二行元素
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
# 为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值
# 比如，对第一行元素所有列元素赋值12
X[1:2, :] = 12
X

tensor([[ 0.,  1.,  2.,  3.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5 转换为其他Python对象
将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。torch张量和numpy数
组将共享它们的底层内存，就地操作更改⼀个张量也会同时更改另⼀个张量。

In [35]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

要将⼤⼩为1的张量转换为Python标量，我们可以调⽤item函数或Python的内置函数:

In [36]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)