In [30]:
import torch
import warnings
warnings.filterwarnings('ignore')

# 3.1 张量

In [31]:
# 标量
a = torch.tensor(1.2)
a 

tensor(1.2000)

In [32]:
# 向量
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [33]:
# 矩阵
X = torch.arange(12).reshape((3, 4))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [34]:
# 三阶张量
X = torch.arange(24, dtype=torch.float32).reshape((2, 3, 4))
X

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

# 3.2 张量运算

In [69]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = X.clone()
a = 2
X, X + Y, X * (X + Y), X + a, X.T

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.]]),
 tensor([[  0.,   2.,   8.,  18.],
         [ 32.,  50.,  72.,  98.],
         [128., 162., 200., 242.]]),
 tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.]]),
 tensor([[ 0.,  4.,  8.],
         [ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.]]))

# 3.3 张量降维

In [36]:
# sum(), mean()
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [37]:
X.sum()

tensor(66.)

In [38]:
X.sum(axis=0)

tensor([12., 15., 18., 21.])

In [39]:
X.sum(axis=1)

tensor([ 6., 22., 38.])

In [42]:
X.mean(axis=0)

tensor([4., 5., 6., 7.])

In [43]:
X.mean(axis=1)

tensor([1.5000, 5.5000, 9.5000])

In [44]:
# 元素个数：numel
X.numel()

12

In [45]:
X.sum() / X.numel()

tensor(5.5000)

# 3.4 非降维求和
但是，有时在调⽤函数来计算总和或均值时保持轴数不变会很有⽤,例如，由于sum_A在对每⾏进⾏求和后仍保持两个轴，我们可以通过⼴播将A除以sum_A。

In [48]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [47]:
X.sum(axis=1, keepdims=True)

tensor([[ 6.],
        [22.],
        [38.]])

In [49]:
X / X.sum()

tensor([[0.0000, 0.0152, 0.0303, 0.0455],
        [0.0606, 0.0758, 0.0909, 0.1061],
        [0.1212, 0.1364, 0.1515, 0.1667]])

如果我们想沿某个轴计算A元素的累积总和，⽐如axis=0（按⾏计算），我们可以调⽤cumsum函数。此函数
不会沿任何轴降低输⼊张量的维度。

In [50]:
X.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.]])

# 3.5 点积 （Dot Product）
我们已经学习了按元素操作、求和及平均值。另⼀个最基本的操作之⼀是点积：给定两个向量$\mathbf{x},\mathbf{y}\in\mathbb{R}^d$，
它们的*点积*（dot product）$\mathbf{x}^\top\mathbf{y}$
（或$\langle\mathbf{x},\mathbf{y}\rangle$）
是相同位置的按元素乘积的和：$\mathbf{x}^\top \mathbf{y} = \sum_{i=1}^{d} x_i y_i$。


In [51]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([1., 2., 3., 4.]), tensor([1., 1., 1., 1.]), tensor(10.))

注意，(**我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积**)：


In [53]:
(x * y).sum(), torch.sum(x * y)

(tensor(10.), tensor(10.))

# 3.6矩阵-向量积
义的矩阵$\mathbf{A} \in \mathbb{R}^{m \times n}$和向量$\mathbf{x} \in \mathbb{R}^n$。
让我们将矩阵$\mathbf{A}$用它的行向量表示：

$$\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix},$$

其中每个$\mathbf{a}^\top_{i} \in \mathbb{R}^n$都是行向量，表示矩阵的第$i$行。
[**矩阵向量积$\mathbf{A}\mathbf{x}$是一个长度为$m$的列向量，
其第$i$个元素是点积$\mathbf{a}^\top_i \mathbf{x}$**]：

$$
\mathbf{A}\mathbf{x}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix}\mathbf{x}
= \begin{bmatrix}
 \mathbf{a}^\top_{1} \mathbf{x}  \\
 \mathbf{a}^\top_{2} \mathbf{x} \\
\vdots\\
 \mathbf{a}^\top_{m} \mathbf{x}\\
\end{bmatrix}.
$$

当我们为矩阵`A`和向量`x`调用`torch.mv(A, x)`时，会执行矩阵-向量积。
注意，`A`的列维数（沿轴1的长度）必须与`x`的维数（其长度）相同。

In [63]:
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)
x = torch.arange(4, dtype=torch.float32)
A, x, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([0., 1., 2., 3.]),
 tensor([14., 38., 62.]))

# 3.7 矩阵乘法

In [64]:
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)
B = torch.arange(12, dtype=torch.float32).reshape(4, 3)
torch.mm(A, B)

tensor([[ 42.,  48.,  54.],
        [114., 136., 158.],
        [186., 224., 262.]])

# 3.8 范数

$L_2$范数:

In [65]:
x

tensor([0., 1., 2., 3.])

In [66]:
torch.norm(x)

tensor(3.7417)

$L_1$范数：

In [67]:
torch.abs(x).sum()

tensor(6.)

矩阵富比尼范数（矩阵元素平方和的平方根）：

In [68]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
torch.norm(X)

tensor(22.4944)